Allow routers to be seen when changing L3 plugin
noironetworks/networking-cisco pull request #22
Opened 2016-09-19 16:44 UTC by tbachman

If a neutron router was created by a different L3 plugin, when
the Cisco Router Service Plugin is selected and neutron restarted,
then the pre-existing neutron router will not be found when queried
because it doesn't have a RouterHostingDeviceBinding. This patch
adds the namespace binding for routers that don't have one, which
allows them to be seen when queried.

Signed-off-by: Thomas Bachman <tbachman@yahoo.com>

2016-09-19 18:39 UTC, kentwu1 commented on networking_cisco/plugins/cisco/db/l3/l3_router_appliance_db.py
> +        router_db[routertype.TYPE_ATTR] = router_type_id
It doesn't seem these 4 router_db[] assignments are needed here.....

2016-09-19 18:41 UTC, kentwu1 commented on networking_cisco/tests/unit/cisco/l3/test_l3_router_appliance_plugin.py
> +        hdb = query.first()
let's enhance the test a bit like to use router_id to make sure its indeed the one we got.

2016-09-19 18:42 UTC, kentwu1 requested changes

2016-09-19 18:42 UTC, tbachman commented on networking_cisco/plugins/cisco/db/l3/l3_router_appliance_db.py
> +        router_db[routertype.TYPE_ATTR] = router_type_id
Agreed -- will remove.

2016-09-19 18:42 UTC, tbachman commented on networking_cisco/tests/unit/cisco/l3/test_l3_router_appliance_plugin.py
> +        hdb = query.first()
sure -- will add and resubmit.

2016-09-19 19:27 UTC, tbachman commented
Pushed changes, addressing reviewer comments.

2016-09-20 17:00 UTC, tbachman commented
Added fix for UTs.

2016-09-20 17:26 UTC, kentwu1 commented on networking_cisco/tests/unit/cisco/l3/test_l3_router_appliance_plugin.py
> +        self.assertIsNotNone(hdb)
can we add self.assertEqual(hdb['router_id'], r['id']) here also?

2016-09-20 17:27 UTC, kentwu1 approved these changes

2016-09-20 17:27 UTC, tbachman commented on networking_cisco/tests/unit/cisco/l3/test_l3_router_appliance_plugin.py
> +        self.assertIsNotNone(hdb)
Yeah -- missed that. Will add.

2016-09-20 17:36 UTC, tbachman commented
pushed new patch, addressing reviewer comments.

2016-09-20 17:37 UTC, merged